### ISSUE TITLE
Please add this project to crates.io

### ISSUE THREAD

**Issue by hh9527** [rschmitt/heatseeker#21]

**Comment by rschmitt** [comment]
Is there any particular reason? Heatseeker isn't usable as a library, and I don't think I want to encourage people to install the binary through Crates.io. Gary Bernhardt has a similar stance regarding Selecta:

> Selecta is not installable as a Ruby gem! Gems are only good for application-specific tools. You want Selecta available at all times. If it were a gem, it would sometimes disappear when switching Rubies, gemsets, etc.

**Comment by iliekturtles** [comment]
If on crates.io users could use `cargo install heatseeker` as an additional installation option.

**Comment by rschmitt** [comment]
https://crates.io/crates/heatseeker
