### ISSUE TITLE
parse ansi colors?

### ISSUE THREAD

**Issue by hh9527** [rschmitt/heatseeker#23]
so we can use like this:
```shell
rg --color ansi unwrap_or | hs | xargs vi 
```

skim (https://github.com/lotabout/skim) support this feature.

**Comment by rschmitt** [comment]
Can you explain exactly how it is "parsing" the ANSI color codes?

**Comment by hh9527** [comment]
> Can you explain exactly how it is "parsing" the ANSI color codes?

In this command:

`rg --color ansi unwrap_or | hs | xargs vi`

`rg --color ansi unwrap_or` will output stream with color escaped sequence, and `hs` could parsing it, and add some additional highlight colors to it, like this:

file1.rs:10 foo.**unwrap_or**(Foo::default())

`unwrap_or` is highlighted by `rg`

after `hs` process, it will display (assume user input 'def'):

file1.rs:10 foo.**unwrap_or**(Foo::**def**ault())

`def` is highlighted by `hs`

**Comment by rschmitt** [comment]
Currently, ANSI color codes pass through heatseeker more or less transparently. Is the idea for heatseeker to strip color codes from the choices it writes to stdout?
