### ISSUE TITLE
The hs command appears to hang on MSYS shells/Git Bash (Windows)

### ISSUE THREAD

**Issue by mistodon** [rschmitt/heatseeker#25]
I installed via Chocolatey. It works correctly in a Windows cmd shell, but running `ls | hs.exe` just hangs forever in an MSYS shell or Git Bash shell.

(Possibly also worth noting that `ls | selecta` in the same shell gives me an error:
`selecta:829:in 'spawn': No such file or directory - /dev/tty (Errno::ENOENT)`)

**Comment by mistodon** [comment]
It looks like this is actually a problem with MSYS: https://stackoverflow.com/questions/16555260/msys-not-opening-programs-interactively

Running `ls | winpty hs` however results in: `stdin is not a tty`

**Comment by rschmitt** [comment]
I think a Cygwin build of Heatseeker will be required for MSYS. This isn't something I've attempted before.

**Comment by muellerj** [comment]
Also see #15.
