### ISSUE TITLE
Exiting via ^C changes terminal settings

### ISSUE THREAD

**Issue by cdlm** [rschmitt/heatseeker#26]
After cancelling `hs` using control-C, the terminal is left in a different state. The return key results in `^M` instead of newlines, [as described here](https://askubuntu.com/questions/441744/pressing-enter-produces-m-instead-of-a-newline).

This can be confirmed by comparing the output of `stty -a | grep icrnl` before and after running `hs` and pressing ^C. Pressing ^G instead of ^C behaves correctly.

**Comment by rschmitt** [comment]
That's a good point. I've personally always used `^G`, but there's no reason that I couldn't trap `^C`. I think I would also need to essentially reimplement https://github.com/garybernhardt/selecta/commit/7a70fce0fab8f74212fcfce9642eacc40c3321ed.
