### ISSUE TITLE
Use spacebar for selections as well as CTRL+T

### ISSUE THREAD

**Issue by balupton** [rschmitt/heatseeker#27]
It would never have occurred to me in a million years to use CTRL+T as the selector, my first guess would always be spacebar, which is what other apps I've experienced in the past have used.

Is it possible to add support for spacebar?

**Comment by rschmitt** [comment]
Spaces are like any other character that can appear in a selection; they don't receive special handling. Have you encountered *command line applications* that use the spacebar in this way?

**Comment by balupton** [comment]
Having thought about this more, as heat seeker also does filtering, I agree this suggestion does not make sense. It makes more sense for something like https://github.com/fisherman/choices
