### ISSUE TITLE
Keyboard sometimes unresponsive in PowerShell after invoking heatseeker

### ISSUE THREAD

**Issue by chigby** [rschmitt/heatseeker#36]
Hi,

I'm using heatseeker and _after_ I activate it, some console programs appear not to be able to receive keyboard input, particularly ones that take over the console and one might want to `^C` out of. The shell itself is fine, and not all console programs seem affected.

Steps to reproduce.

1. Open PowerShell
2. Run `echo a | hs` and press enter
3. Run `ping -t google.com`

Expected outcome:

I should be able to press `Control+C` for ping to stop pinging.

Actual outcome: 

Pressing `Control+C` does not stop pinging. 

Remarks:

`ping` is not the only program affected by this. I first noticed this when running the `hugo` server, but I don't think everyone has that installed. The node-js repl is notably _not_ affected, and in fact kind of "resets" the state of the shell. That is to say, I can run `echo a | hs`, press enter, run `node`, exit that repl normally, then `ping -t google.com` and I will be able to `^C` out of that as I'd expect. I have no idea if that would be helpful to you for troubleshooting.

System information:

```
hs --version
heatseeker 1.6.0-3a43ab5 (built 2018-11-11 21:32:06 -0000 for x86_64-pc-windows-msvc)

$PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      1      3

[Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17763.0 Microsoft Windows NT 10.0.17763.0
```

Thank you. If there's anything else you need from me that would be useful, please let me know.

**Comment by rschmitt** [comment]
Thanks for the report. There was an uncannily similar bug on the POSIX side until v1.6.0 (see c64fed2edfe20e1ba424acf13c145f3d56229a14).
