### ISSUE TITLE
Permit scrolling the results

### ISSUE THREAD

**Issue by cormacrelf** [rschmitt/heatseeker#37]
Sometimes you want to use heatseeker to simply pick things from a list without specifically searching for one or two of them. One use case I just tried is:

```
brew outdated | awk '{print $1}' | hs | xargs brew upgrade
```

This task kinda needs to be done by looking through all the outdated packages and wondering if you want each one upgraded or not. But you can't do that -- scrolling in heatseeker just wraps around to the top, and you can only ever see one screenful of content. I felt pretty silly just now typing `a... ^T^T, backspace, b... ^T^T^T`. You could also reduce your font size to like 5px and increase the line count... but this is not ideal either.

I can also imagine it being difficult to narrow down lots of very similar results, i.e. more than a screenful of `/home/me/projects/bitte/neverending/path/segments/file_a.txt`.

I understand `selecta` does not scroll either, but aim high, why not.

**Comment by rschmitt** [comment]
I think this is worth a try.

**Comment by rschmitt** [comment]
I added a basic version of this feature in [the most recent commit](https://github.com/rschmitt/heatseeker/commit/1a5ce9b8b4433e32fe8b905ff958524727529f91). I'd still like to add support for Home/End/PgUp/PgDown before releasing it.

**Comment by rschmitt** [comment]
This feature is now fully implemented in a6d052391c3328a0676075b30459b6777d407712 and bde64f1c5f5b62d3f32250ed2e5b37e513af871d. It will be included in release 1.7.0.
