### ISSUE TITLE
PSReadLine default keybind for Ctrl-S

### ISSUE THREAD

**Issue by hrxn** [rschmitt/heatseeker#39]
As far as I know, <kbd>Ctrl</kbd>+<kbd>s</kbd> is the keybind for the function to search history forward interactively, set as a pre-defined default by PSReadLine.

Is this something that should maybe be mentioned in the [example](https://github.com/rschmitt/heatseeker#powershell) in `README.md`?

And if I may ask, did you pick Ctrl-S intentionally here? I mean that interactive history search forward does not really seem useful to me. Can't remember that I've actually used it for myself.

**Comment by hrxn** [comment]
Ping.

**Comment by rschmitt** [comment]
I wasn't aware of the default ^S shortcut in PowerShell. That shortcut comes from [Selecta's examples](https://github.com/garybernhardt/selecta/blob/master/EXAMPLES.md#zsh-insert-fuzzy-found-paths-directly-into-the-shell-command-line), where it's used in the context of zsh integration. In that case, you're overriding a keybinding for a totally unrelated function, namely flow control.
